/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "tests/func_tests/test_s21_memset.check"
 * instead.
 */

#include <check.h>

#include "../../s21_string.h"
#include "../s21_string_tests.h"

#define N 100
#define C 'a'

START_TEST(normal_data) {
  char s21_res[N];
  char orig_res[N];
  s21_memset(s21_res, C, N);
  memset(orig_res, C, N);

  for (int i = 0; i < N; i++) ck_assert_int_eq(s21_res[i], orig_res[i]);
}
END_TEST

START_TEST(zero_data) {
  char c = 0;
  char s21_res[N];
  char orig_res[N];
  s21_memset(s21_res, c, N);
  memset(orig_res, c, N);

  for (int i = 0; i < N; i++) ck_assert_int_eq(s21_res[i], orig_res[i]);
}
END_TEST

START_TEST(len_smaller_n) {
  char s21_res[N - 1];
  char orig_res[N - 1];
  s21_memset(s21_res, C, N);
  memset(orig_res, C, N - 1);
  for (int i = 0; i < N - 1; i++) ck_assert_int_eq(s21_res[i], orig_res[i]);
}
END_TEST

START_TEST(null_data) {
  char *res = s21_memset(S21_NULL, C, N);
  char *expected = S21_NULL;
  ck_assert_ptr_eq(res, expected);
}
END_TEST

int test_s21_memset(void) {
  Suite *s1 = suite_create("s21_memset");
  TCase *tc1_1 = tcase_create("s21_memset");
  SRunner *sr = srunner_create(s1);
  int nf;

  tcase_set_timeout(tc1_1, 10);
  system("mkdir -p tests/logs");
  char full_filename[1024];
  sprintf(full_filename, "tests/logs/%s.log", __FILE_NAME__);
  srunner_set_log(sr, full_filename);

  suite_add_tcase(s1, tc1_1);
  tcase_add_test(tc1_1, normal_data);
  tcase_add_test(tc1_1, zero_data);
  tcase_add_test(tc1_1, len_smaller_n);
  tcase_add_test(tc1_1, null_data);

  srunner_run_all(sr, CK_ENV);
  nf = srunner_ntests_failed(sr);
  srunner_free(sr);

  return nf == 0 ? 0 : 1;
}
