/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file
 * "tests/func_tests/tests_check/test_s21_atoi.check" instead.
 */

#include <check.h>

#include "../s21_string_tests.h"

START_TEST(normal_data) {
  const char *str = "12345";
  int s21_res = s21_atoi(str);
  int orig_res = atoi(str);
  ck_assert_int_eq(s21_res, orig_res);
}
END_TEST

START_TEST(null_str) {
  const char *str = NULL;
  int s21_res = s21_atoi(str);
  int orig_res = 0;
  ck_assert_int_eq(s21_res, orig_res);
}
END_TEST

START_TEST(empty_str) {
  const char *str = "";
  int s21_res = s21_atoi(str);
  int orig_res = atoi(str);
  ck_assert_int_eq(s21_res, orig_res);
}
END_TEST

START_TEST(int_max) {
  const char *str = "2147483647";
  int s21_res = s21_atoi(str);
  int orig_res = atoi(str);
  ck_assert_int_eq(s21_res, orig_res);
}
END_TEST

START_TEST(int_min) {
  const char *str = "-2147483648";
  int s21_res = s21_atoi(str);
  int orig_res = atoi(str);
  ck_assert_int_eq(s21_res, orig_res);
}
END_TEST

START_TEST(zero) {
  const char *str = "0";
  int s21_res = s21_atoi(str);
  int orig_res = atoi(str);
  ck_assert_int_eq(s21_res, orig_res);
}
END_TEST

START_TEST(negative) {
  const char *str = "-12345";
  int s21_res = s21_atoi(str);
  int orig_res = atoi(str);
  ck_assert_int_eq(s21_res, orig_res);
}
END_TEST

START_TEST(lower_than_int_min) {
  const char *str = "-2147483649999";
  int s21_res = s21_atoi(str);
  int orig_res = atoi(str);
  ck_assert_int_eq(s21_res, orig_res);
}
END_TEST

START_TEST(higher_than_int_max) {
  const char *str = "2147483648";
  int s21_res = s21_atoi(str);
  int orig_res = INT_MAX;
  ck_assert_int_eq(s21_res, orig_res);
}
END_TEST

START_TEST(spaces) {
  const char *str = "   12345   ";
  int s21_res = s21_atoi(str);
  int orig_res = atoi(str);
  ck_assert_int_eq(s21_res, orig_res);
}
END_TEST

START_TEST(tabs) {
  const char *str = "\t\t12345\t\t";
  int s21_res = s21_atoi(str);
  int orig_res = atoi(str);
  ck_assert_int_eq(s21_res, orig_res);
}
END_TEST

START_TEST(newlines) {
  const char *str = "\n\n12345\n\n";
  int s21_res = s21_atoi(str);
  int orig_res = atoi(str);
  ck_assert_int_eq(s21_res, orig_res);
}
END_TEST

START_TEST(num_and_str) {
  const char *str = "12345abc";
  int s21_res = s21_atoi(str);
  int orig_res = atoi(str);
  ck_assert_int_eq(s21_res, orig_res);
  ck_assert_str_eq(str, "12345abc");
}
END_TEST

START_TEST(spaces_and_negative) {
  const char *str = "   -12345   ";
  int s21_res = s21_atoi(str);
  int orig_res = atoi(str);
  ck_assert_int_eq(s21_res, orig_res);
}
END_TEST

START_TEST(tabs_and_plus) {
  const char *str = "\t\t+12345\t\t";
  int s21_res = s21_atoi(str);
  int orig_res = atoi(str);
  ck_assert_int_eq(s21_res, orig_res);
}
END_TEST

START_TEST(test_s21_atoi_overflow_positive) {
  const char *str = "2147483648";
  int result = s21_atoi(str);
  ck_assert_int_eq(result, INT_MAX);
}
END_TEST

START_TEST(test_s21_atoi_overflow_negative) {
  const char *str = "-2147483649";
  int result = s21_atoi(str);
  ck_assert_int_eq(result, -1999);
}
END_TEST

int test_s21_atoi(void) {
  Suite *s1 = suite_create("s21_atoi");
  TCase *tc1_1 = tcase_create("s21_atoi");
  SRunner *sr = srunner_create(s1);
  int nf;

  system("mkdir -p tests/logs");
  char full_filename[1024];
  sprintf(full_filename, "tests/logs/%s.log", __FILE_NAME__);
  srunner_set_log(sr, full_filename);

  suite_add_tcase(s1, tc1_1);
  tcase_add_test(tc1_1, normal_data);
  tcase_add_test(tc1_1, null_str);
  tcase_add_test(tc1_1, empty_str);
  tcase_add_test(tc1_1, int_max);
  tcase_add_test(tc1_1, int_min);
  tcase_add_test(tc1_1, zero);
  tcase_add_test(tc1_1, negative);
  tcase_add_test(tc1_1, lower_than_int_min);
  tcase_add_test(tc1_1, higher_than_int_max);
  tcase_add_test(tc1_1, spaces);
  tcase_add_test(tc1_1, tabs);
  tcase_add_test(tc1_1, newlines);
  tcase_add_test(tc1_1, num_and_str);
  tcase_add_test(tc1_1, spaces_and_negative);
  tcase_add_test(tc1_1, tabs_and_plus);
  tcase_add_test(tc1_1, test_s21_atoi_overflow_positive);
  tcase_add_test(tc1_1, test_s21_atoi_overflow_negative);

  srunner_run_all(sr, CK_ENV);
  nf = srunner_ntests_failed(sr);
  srunner_free(sr);

  return nf == 0 ? 0 : 1;
}
