/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file
 * "tests/func_tests/tests_check/tests_ll_to_char.check" instead.
 */

#include <check.h>
#include <float.h>
#include <limits.h>

#include "../s21_string_tests.h"

START_TEST(short_int_to_char) {
  short int nums[] = {0,  1,  2,  3,  4,  5,  6,        7,        8,   9,
                      -1, -2, -3, -4, -5, -6, SHRT_MAX, SHRT_MIN, 555, -9999};

  char s21_out[BUF_SIZE] = {0};
  char orig_out[BUF_SIZE] = {0};
  S21_ITOA(nums[_i], s21_out, 10);
  sprintf(orig_out, "%hd", nums[_i]);
  int result = strcmp(s21_out, orig_out) == 0;
  ck_assert_msg(result, "\n[s21_out: %s]\n[orig_out: %s]\n[input: %hd]",
                s21_out, orig_out, nums[_i]);
}
END_TEST

START_TEST(long_int_to_char) {
  long int nums[] = {0,  1,  2,       3,       4,         5,        6,
                     7,  8,  9,       -1,      -2,        -3,       -4,
                     -5, -6, INT_MAX, INT_MIN, LLONG_MAX, LLONG_MIN};

  char s21_out[BUF_SIZE] = {0};
  char orig_out[BUF_SIZE] = {0};
  S21_ITOA(nums[_i], s21_out, 10);
  sprintf(orig_out, "%ld", nums[_i]);
  int result = strcmp(s21_out, orig_out) == 0;
  ck_assert_msg(result, "\n[s21_out: %s]\n[orig_out: %s]\n[input: %ld]",
                s21_out, orig_out, nums[_i]);
}
END_TEST

START_TEST(long_long_int_to_char) {
  long long int nums[] = {0,  1,  2,       3,       4,         5,        6,
                          7,  8,  9,       -1,      -2,        -3,       -4,
                          -5, -6, INT_MAX, INT_MIN, LLONG_MAX, LLONG_MIN};

  char s21_out[BUF_SIZE] = {0};
  char orig_out[BUF_SIZE] = {0};
  S21_ITOA(nums[_i], s21_out, 10);
  sprintf(orig_out, "%lld", nums[_i]);
  int result = strcmp(s21_out, orig_out) == 0;
  ck_assert_msg(result, "\n[s21_out: %s]\n[orig_out: %s]\n[input: %lld]",
                s21_out, orig_out, nums[_i]);
}
END_TEST

START_TEST(unsigned_short_int_to_char) {
  unsigned short int nums[] = {0,  1,  2,        3,        4,   5,    6,
                               7,  8,  9,        -1,       -2,  -3,   -4,
                               -5, -6, SHRT_MAX, SHRT_MIN, 555, -9999};

  char s21_out[BUF_SIZE] = {0};
  char orig_out[BUF_SIZE] = {0};
  S21_ITOA(nums[_i], s21_out, 10);
  sprintf(orig_out, "%hu", nums[_i]);
  int result = strcmp(s21_out, orig_out) == 0;
  ck_assert_msg(result, "\n[s21_out: %s]\n[orig_out: %s]\n[input: %hu]",
                s21_out, orig_out, nums[_i]);
}
END_TEST

START_TEST(unsigned_long_int_to_char) {
  unsigned long int nums[] = {0,  1,  2,       3,       4,         5,        6,
                              7,  8,  9,       -1,      -2,        -3,       -4,
                              -5, -6, INT_MAX, INT_MIN, LLONG_MAX, LLONG_MIN};

  char s21_out[BUF_SIZE] = {0};
  char orig_out[BUF_SIZE] = {0};
  S21_ITOA(nums[_i], s21_out, 10);
  sprintf(orig_out, "%lu", nums[_i]);
  int result = strcmp(s21_out, orig_out) == 0;
  ck_assert_msg(result, "\n[s21_out: %s]\n[orig_out: %s]\n[input: %lu]",
                s21_out, orig_out, nums[_i]);
}
END_TEST

START_TEST(unsigned_int_to_char) {
  unsigned int nums[] = {
      0,  1,  2,  3,  4,  5,  6,       7,       8,        9,
      -1, -2, -3, -4, -5, -6, INT_MAX, INT_MIN, UINT_MAX, UINT_MAX - 1000};

  char s21_out[BUF_SIZE] = {0};
  char orig_out[BUF_SIZE] = {0};
  S21_ITOA(nums[_i], s21_out, 10);
  sprintf(orig_out, "%u", nums[_i]);
  int result = strcmp(s21_out, orig_out) == 0;
  ck_assert_msg(result, "\n[s21_out: %s]\n[orig_out: %s]\n[input: %u]", s21_out,
                orig_out, nums[_i]);
}

START_TEST(unsigned_long_long_int_to_char) {
  unsigned long long int nums[] = {
      0,  1,  2,  3,  4,  5,  6,       7,       8,         9,
      -1, -2, -3, -4, -5, -6, INT_MAX, INT_MIN, LLONG_MAX, LLONG_MIN};

  char s21_out[BUF_SIZE] = {0};
  char orig_out[BUF_SIZE] = {0};
  S21_ITOA(nums[_i], s21_out, 10);
  sprintf(orig_out, "%llu", nums[_i]);
  int result = strcmp(s21_out, orig_out) == 0;
  ck_assert_msg(result, "\n[s21_out: %s]\n[orig_out: %s]\n[input: %llu]",
                s21_out, orig_out, nums[_i]);
}
END_TEST

START_TEST(unsigned_short_int_oct_to_char) {
  unsigned short int nums[] = {0,  1,  2,        3,        4,   5,    6,
                               7,  8,  9,        -1,       -2,  -3,   -4,
                               -5, -6, SHRT_MAX, SHRT_MIN, 555, -9999};

  char s21_out[BUF_SIZE] = {0};
  char orig_out[BUF_SIZE] = {0};
  S21_ITOA(nums[_i], s21_out, 8);
  sprintf(orig_out, "%ho", nums[_i]);
  int result = strcmp(s21_out, orig_out) == 0;
  ck_assert_msg(result, "\n[s21_out: %s]\n[orig_out: %s]\n[input: %ho]",
                s21_out, orig_out, nums[_i]);
}
END_TEST

START_TEST(unsigned_long_long_int_hex_to_char) {
  unsigned long long int nums[] = {
      0,  1,  2,  3,  4,  5,  6,       7,       8,         9,
      -1, -2, -3, -4, -5, -6, INT_MAX, INT_MIN, LLONG_MAX, LLONG_MIN};

  char s21_out[BUF_SIZE] = {0};
  char orig_out[BUF_SIZE] = {0};
  S21_ITOA(nums[_i], s21_out, 16);
  sprintf(orig_out, "%llx", nums[_i]);
  int result = strcmp(s21_out, orig_out) == 0;
  ck_assert_msg(result, "\n[s21_out: %s]\n[orig_out: %s]\n[input: %llx]",
                s21_out, orig_out, nums[_i]);
}
END_TEST

int test_s21_llitoa(void) {
  Suite *s1 = suite_create("digits_to_str");
  TCase *tc1_1 = tcase_create("lli_to_str");
  SRunner *sr = srunner_create(s1);
  int nf;

  /* User-specified pre-run code */
  system("mkdir -p tests/logs");
  char full_filename[BUF_SIZE];
  sprintf(full_filename, "tests/logs/%s.log", __FILE_NAME__);
  srunner_set_log(sr, full_filename);

  suite_add_tcase(s1, tc1_1);
  tcase_add_loop_test(tc1_1, short_int_to_char, 0, 20);
  tcase_add_loop_test(tc1_1, unsigned_int_to_char, 0, 20);
  tcase_add_loop_test(tc1_1, long_int_to_char, 0, 20);
  tcase_add_loop_test(tc1_1, long_long_int_to_char, 0, 20);
  tcase_add_loop_test(tc1_1, unsigned_short_int_to_char, 0, 20);
  tcase_add_loop_test(tc1_1, unsigned_long_int_to_char, 0, 20);
  tcase_add_loop_test(tc1_1, unsigned_long_long_int_to_char, 0, 20);
  tcase_add_loop_test(tc1_1, unsigned_short_int_oct_to_char, 0, 20);
  tcase_add_loop_test(tc1_1, unsigned_long_long_int_hex_to_char, 0, 20);

  srunner_run_all(sr, CK_ENV);
  nf = srunner_ntests_failed(sr);
  srunner_free(sr);

  /* User-specified post-run code */
  return nf;
}
