/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file
 * "tests/func_tests/tests_check/test_s21_strlen.check" instead.
 */

#include <check.h>

#include "../../s21_string.h"
#include "../s21_string_tests.h"

#define LEN 100

START_TEST(normal_data) {
  const char str[LEN] = "Hello world";
  int s21_res = s21_strlen(str);
  int orig_res = strlen(str);
  ck_assert_int_eq(s21_res, orig_res);
}
END_TEST

START_TEST(null_str) {
  const char *str = NULL;
  int s21_res = s21_strlen(str);
  int orig_res = 0;
  ck_assert_int_eq(s21_res, orig_res);
}
END_TEST

START_TEST(zero_data) {
  const char str[LEN] = "Hell\0o world";
  int s21_res = s21_strlen(str);
  int orig_res = strlen(str);
  ck_assert_int_eq(s21_res, orig_res);
}
END_TEST

START_TEST(empty_str) {
  const char str[LEN] = "";
  int s21_res = s21_strlen(str);
  int orig_res = strlen(str);
  ck_assert_int_eq(s21_res, orig_res);
}
END_TEST

START_TEST(long_str) {
  char str[LEN * LEN];
  memset(str, 'a', LEN * LEN - 1);
  int s21_res = s21_strlen(str);
  int orig_res = strlen(str);
  ck_assert_int_eq(s21_res, orig_res);
}
END_TEST

int test_s21_strlen(void) {
  Suite *s1 = suite_create("s21_strlen");
  TCase *tc1_1 = tcase_create("s21_strlen");
  SRunner *sr = srunner_create(s1);
  int nf;

  /* User-specified pre-run code */
  tcase_set_timeout(tc1_1, 10);
  system("mkdir -p tests/logs");
  char full_filename[1024];
  sprintf(full_filename, "tests/logs/%s.log", __FILE_NAME__);
  srunner_set_log(sr, full_filename);

  suite_add_tcase(s1, tc1_1);
  tcase_add_test(tc1_1, normal_data);
  tcase_add_test(tc1_1, null_str);
  tcase_add_test(tc1_1, zero_data);
  tcase_add_test(tc1_1, empty_str);
  tcase_add_test(tc1_1, long_str);

  srunner_run_all(sr, CK_ENV);
  nf = srunner_ntests_failed(sr);
  srunner_free(sr);

  return nf == 0 ? 0 : 1;
}
