/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file
 * "tests/func_tests/tests_check/test_s21_strchr.check" instead.
 */

#include <check.h>
#include <stdio.h>

#include "../../s21_string.h"
#include "../s21_string_tests.h"

#define LEN 100

START_TEST(normal_data) {
  const char str[LEN] = "Hello world";
  char *s21_res = s21_strchr(str, 'o');
  char *orig_res = strchr(str, 'o');
  ck_assert_ptr_eq(s21_res, orig_res);
}
END_TEST

START_TEST(another_normal_data) {
  const char str[LEN] = "Hello world";
  char *s21_res = s21_strchr(str, 'w');
  char *orig_res = strchr(str, 'w');
  ck_assert_ptr_eq(s21_res, orig_res);
}
END_TEST

START_TEST(null_str) {
  const char *str = NULL;
  char *s21_res = s21_strchr(str, 'o');
  char *orig_res = NULL;
  ck_assert_ptr_eq(s21_res, orig_res);
}
END_TEST

START_TEST(zero_char) {
  const char str[LEN] = "Hello world";
  char *s21_res = s21_strchr(str, '\0');
  char *orig_res = strchr(str, '\0');
  ck_assert_ptr_eq(s21_res, orig_res);
}
END_TEST

START_TEST(empty_str) {
  const char str[LEN] = "";
  char *s21_res = s21_strchr(str, 'o');
  char *orig_res = strchr(str, 'o');
  ck_assert_ptr_eq(s21_res, orig_res);
}
END_TEST

START_TEST(zero_data) {
  const char str[LEN] = "Hell\0o world";
  char *s21_res = s21_strchr(str, 'o');
  char *orig_res = strchr(str, 'o');
  ck_assert_ptr_eq(s21_res, orig_res);
}
END_TEST

START_TEST(wrong_char) {
  const char str[LEN] = "Hello world";
  char *s21_res = s21_strchr(str, 'z');
  char *orig_res = strchr(str, 'z');
  ck_assert_ptr_eq(s21_res, orig_res);
}
END_TEST

START_TEST(long_str) {
  char *str = calloc(LEN * LEN * LEN, sizeof(char));
  memset(str, 'a', LEN * LEN * LEN - 1);
  str[LEN * LEN] = 'b';
  char *s21_res = s21_strchr(str, 'b');
  char *orig_res = strchr(str, 'b');
  ck_assert_ptr_eq(s21_res, orig_res);
}
END_TEST

int test_s21_strchr(void) {
  Suite *s1 = suite_create("s21_strchr");
  TCase *tc1_1 = tcase_create("s21_strchr");
  SRunner *sr = srunner_create(s1);
  int nf;

  /* User-specified pre-run code */
  system("mkdir -p tests/logs");
  char full_filename[1024];
  sprintf(full_filename, "tests/logs/%s.log", __FILE_NAME__);
  srunner_set_log(sr, full_filename);

  suite_add_tcase(s1, tc1_1);
  tcase_add_test(tc1_1, normal_data);
  tcase_add_test(tc1_1, another_normal_data);
  tcase_add_test(tc1_1, null_str);
  tcase_add_test(tc1_1, zero_char);
  tcase_add_test(tc1_1, empty_str);
  tcase_add_test(tc1_1, zero_data);
  tcase_add_test(tc1_1, wrong_char);
  tcase_add_test(tc1_1, long_str);

  srunner_run_all(sr, CK_ENV);
  nf = srunner_ntests_failed(sr);
  srunner_free(sr);

  return nf == 0 ? 0 : 1;
}
